apiVersion: v1
kind: Service
metadata:
  labels:
    app: client
  name: client
  namespace: default
spec:
  externalIPs:
  - 192.168.59.102
  ports:
  - nodePort: 31358
    port: 8081
    targetPort: 8080
  selector:
    app: client
  type: NodePort
