apiVersion: v1
kind: Service
metadata:
  labels:
    app: service
  name: service
  namespace: default
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: service
  type: ClusterIP
